USE [RepPortal];
GO

CREATE NONCLUSTERED INDEX [idx_Nonclustered_RepLoginHistory_RepCode]
ON [dbo].[RepLoginHistory]
([RepCode])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO


USE [RepPortal];
GO

CREATE NONCLUSTERED INDEX [idx_Nonclustered_ReportUsageHistory_RepCode]
ON [dbo].[ReportUsageHistory]
([RepCode])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO
