USE [RepPortal];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[FileDownloadHistory] (
[Id] int IDENTITY(1, 1) NOT NULL,
[RepCode] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DownloadTime] datetime2(0) NULL,
[ResourceIdentifier] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdminUser] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED ([Id] )
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY]
)
ON [PRIMARY];
GO
ALTER TABLE [dbo].[FileDownloadHistory] SET (LOCK_ESCALATION = TABLE);
GO

CREATE NONCLUSTERED INDEX [idx_Nonclustered_FileDownloadHistory_RepCode]
ON [dbo].[FileDownloadHistory]
([RepCode])
WITH
(
PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ONLINE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE
)
ON [PRIMARY];
GO